services:
  frontend:
    container_name: "nextjs-frontend"
    build:
      context: ./src/web
      dockerfile: dev.Dockerfile
    develop:
      watch:
        - path: ./src/web
          target: /app
          action: sync
          ignore:
            - node_modules/
            - .next/
    volumes:
      - ./src/web:/app:rw
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    command: npm run dev
    restart: always
    ports:
      - "${WEB_PORT}:3000"
