// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParticipantManager.API.Data;

#nullable disable

namespace ParticipantManager.API.Migrations
{
    [DbContext(typeof(ParticipantManagerDbContext))]
    [Migration("20250303103457_refactorPathwayTypeAssignment")]
    partial class refactorPathwayTypeAssignment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParticipantManager.API.Models.Encounter", b =>
                {
                    b.Property<Guid>("EncounterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EncounterId");

                    b.HasIndex("EpisodeId");

                    b.ToTable("Encounters");
                });

            modelBuilder.Entity("ParticipantManager.API.Models.Episode", b =>
                {
                    b.Property<Guid>("EpisodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PathwayTypeAssignmentEnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PathwayVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EpisodeId");

                    b.HasIndex("PathwayTypeAssignmentEnrollmentId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("ParticipantManager.API.Models.Participant", b =>
                {
                    b.Property<Guid>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("NHSNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ParticipantId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("ParticipantManager.API.Models.PathwayTypeEnrollment", b =>
                {
                    b.Property<Guid>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LapsedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextActionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PathwayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PathwayTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ScreeningName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("PathwayTypeAssignments");
                });

            modelBuilder.Entity("ParticipantManager.API.Models.Encounter", b =>
                {
                    b.HasOne("ParticipantManager.API.Models.Episode", null)
                        .WithMany("Encounters")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ParticipantManager.API.Models.Episode", b =>
                {
                    b.HasOne("ParticipantManager.API.Models.PathwayTypeEnrollment", "PathwayTypeAssignment")
                        .WithMany("Episodes")
                        .HasForeignKey("PathwayTypeAssignmentEnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PathwayTypeAssignment");
                });

            modelBuilder.Entity("ParticipantManager.API.Models.PathwayTypeEnrollment", b =>
                {
                    b.HasOne("ParticipantManager.API.Models.Participant", "Participant")
                        .WithMany("PathwayTypeAssignments")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("ParticipantManager.API.Models.Episode", b =>
                {
                    b.Navigation("Encounters");
                });

            modelBuilder.Entity("ParticipantManager.API.Models.Participant", b =>
                {
                    b.Navigation("PathwayTypeAssignments");
                });

            modelBuilder.Entity("ParticipantManager.API.Models.PathwayTypeEnrollment", b =>
                {
                    b.Navigation("Episodes");
                });
#pragma warning restore 612, 618
        }
    }
}
