// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParticipantManager.API.Data;

#nullable disable

namespace ParticipantManager.API.Migrations
{
    [DbContext(typeof(ParticipantManagerDbContext))]
    [Migration("20250324162109_changing_some_properties_to_be_required")]
    partial class changing_some_properties_to_be_required
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParticipantManager.API.Models.Encounter", b =>
                {
                    b.Property<Guid>("EncounterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EncounterId");

                    b.HasIndex("EpisodeId");

                    b.ToTable("Encounters");
                });

            modelBuilder.Entity("ParticipantManager.API.Models.Episode", b =>
                {
                    b.Property<Guid>("EpisodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnrolmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PathwayTypeEnrolmentEnrolmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PathwayVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EpisodeId");

                    b.HasIndex("PathwayTypeEnrolmentEnrolmentId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("ParticipantManager.API.Models.Participant", b =>
                {
                    b.Property<Guid>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NhsNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParticipantId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("ParticipantManager.API.Models.PathwayTypeEnrolment", b =>
                {
                    b.Property<Guid>("EnrolmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EnrolmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LapsedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextActionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PathwayTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PathwayTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScreeningName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnrolmentId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("PathwayTypeEnrolments");
                });

            modelBuilder.Entity("ParticipantManager.API.Models.Encounter", b =>
                {
                    b.HasOne("ParticipantManager.API.Models.Episode", null)
                        .WithMany("Encounters")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ParticipantManager.API.Models.Episode", b =>
                {
                    b.HasOne("ParticipantManager.API.Models.PathwayTypeEnrolment", "PathwayTypeEnrolment")
                        .WithMany("Episodes")
                        .HasForeignKey("PathwayTypeEnrolmentEnrolmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PathwayTypeEnrolment");
                });

            modelBuilder.Entity("ParticipantManager.API.Models.PathwayTypeEnrolment", b =>
                {
                    b.HasOne("ParticipantManager.API.Models.Participant", "Participant")
                        .WithMany("PathwayTypeEnrolments")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("ParticipantManager.API.Models.Episode", b =>
                {
                    b.Navigation("Encounters");
                });

            modelBuilder.Entity("ParticipantManager.API.Models.Participant", b =>
                {
                    b.Navigation("PathwayTypeEnrolments");
                });

            modelBuilder.Entity("ParticipantManager.API.Models.PathwayTypeEnrolment", b =>
                {
                    b.Navigation("Episodes");
                });
#pragma warning restore 612, 618
        }
    }
}
